import {
  common,
  error,
  info,
  primary,
  secondary,
  success,
  warning,
} from './selector'

export const paletteNameList = {
  [common.white]: 'common.white',
  [common.black]: 'common.black',
  [primary.main]: 'primary.main',
  [primary.light]: 'primary.light',
  [primary.dark]: 'primary.dark',
  [primary.contrastText]: 'primary.contrastText',
  [secondary.main]: 'secondary.main',
  [secondary.light]: 'secondary.light',
  [secondary.dark]: 'secondary.dark',
  [secondary.contrastText]: 'secondary.contrastText',
  [error.main]: 'error.main',
  [error.light]: 'error.light',
  [error.dark]: 'error.dark',
  [error.contrastText]: 'error.contrastText',
  [info.main]: 'info.main',
  [info.light]: 'info.light',
  [info.dark]: 'info.dark',
  [warning.main]: 'warning.main',
  [warning.light]: 'warning.light',
  [warning.dark]: 'warning.dark',
  [warning.contrastText]: 'warning.contrastText',
  [success.main]: 'success.main',
  [success.light]: 'success.light',
  [success.dark]: 'success.dark',
  [success.contrastText]: 'success.contrastText',
}
