#!/bin/sh

npx concurrently \
  --kill-others-on-fail \
  --prefix "[{name}]" \
  --names "test,typecheck,lint:fix" \
  --prefix-colors "bgRed.bold.white,bgGreen.bold.white,bgBlue.bold.white,bgMagenta.bold.white" \
    "yarn test --watch=false" \
    "yarn typecheck" \
    "yarn lint:fix"
